### ISSUE TITLE
Error: Could not load upload provider "strapi-provider-upload-aws-s3-enhanced".

### ISSUE THREAD

**Issue by hampton1122** [garretua/strapi-provider-upload-aws-s3-enhanced#8]
I am running **yarn start** or **yarn develop** in my docker container and I get:

`sp-app-strapi  | [2022-02-03 18:03:36.431] debug: ⛔️ Server wasn't able to start properly.
sp-app-strapi  | [2022-02-03 18:03:36.435] error: Could not load upload provider "strapi-provider-upload-aws-s3-enhanced".
sp-app-strapi  | Error: Could not load upload provider "strapi-provider-upload-aws-s3-enhanced".
sp-app-strapi  |     at createProvider (/app/node_modules/@strapi/plugin-upload/server/bootstrap.js:47:11)
sp-app-strapi  |     at Object.module.exports [as bootstrap] (/app/node_modules/@strapi/plugin-upload/server/bootstrap.js:9:38)
sp-app-strapi  |     at Object.bootstrap (/app/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:47)
sp-app-strapi  |     at Object.bootstrap (/app/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:19)
sp-app-strapi  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
sp-app-strapi  |     at async Strapi.runLifecyclesFunctions (/app/node_modules/@strapi/strapi/lib/Strapi.js:461:5)
sp-app-strapi  |     at async Strapi.bootstrap (/app/node_modules/@strapi/strapi/lib/Strapi.js:399:5)
sp-app-strapi  |     at async Strapi.load (/app/node_modules/@strapi/strapi/lib/Strapi.js:408:5)
sp-app-strapi  |     at async Strapi.start (/app/node_modules/@strapi/strapi/lib/Strapi.js:161:9)
sp-app-strapi  | error Command failed with exit code 1.
sp-app-strapi  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Is there some other configuration I need to do to get this plugin to work with **yarn start**?

**Comment by abelcabezaroman** [comment]
If you are using strapi v4 is a problem with sharp package. 

I have fixed this adding sharp 0.30.1 to the package...

In my chase i did a modify so...i am using it locally.
